services:
  php:
    build: ./dockerfiles/php
    ports:
      - 5170:5170
    volumes:
      - ./src:/var/www


  nginx:
    image: "nginx:stable-alpine"
    ports:
      - 80:80
    volumes:
        - ./src:/var/www
        - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
        - php


  db:
    image: mysql:5.6.51
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dockerfiles/db/data:/var/lib/mysql
      - ./dockerfiles/logs:/var/log/mysql
      - ./dockerfiles/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./dockerfiles/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - ./dockerfiles/phpmyadmin/sessions:/sessions
